# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions - updates `uses:` statements in workflows
  - package-ecosystem: "github-actions"
    directory: "/"                  # Where your `.github/workflows/` folder is
    schedule:
      interval: "weekly"

  # Gradle - updates dependencies in build.gradle or build.gradle.kts
  - package-ecosystem: "gradle"
    directory: "/"                  # Adjust if build.gradle is in a subfolder
    schedule:
      interval: "weekly"
